version: '3.8'

services:
  api:
    build: app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 1G

volumes:
  data:
    driver: local